# PAiP Web Developer Guide Pipeline

trigger:
- master
- develop
- version/*

pool:
  vmImage: 'ubuntu-latest'

pr: 
- master
- develop
- version/*

steps:
  - checkout: self
    persistCredentials: true

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'build.py'
    displayName: 'Build README.md'
  
  - script: |
      git add README.md
      git commit -m "[CI] Builded README [skip ci]"
      git push
    displayName: 'Commiting Builded README.md'

  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'
  
  - script: |
      gem install mdl
    displayName: 'Install Markdown Linter'
  
  - script: |
      mdl README.md
    # This task is optional for now
    continueOnError: true
    failOnStderr: false 
    displayName: 'Lint Generated README'
